services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    hostname: cassandra1
    networks:
      - cassandra-net
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
      CASSANDRA_CLUSTER_NAME: SCMDC101
      CASSANDRA_DC: IND_BLR_DC_1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    volumes:
      - C:\Users\ramak\Docker\cassandra-cluster-dev\SCMDC101\IND_BLR_DC_1\cassandra1:/var/lib/cassandra

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    hostname: cassandra2
    networks:
      - cassandra-net
    ports:
      - "9043:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
      CASSANDRA_CLUSTER_NAME: SCMDC101
      CASSANDRA_DC: IND_BLR_DC_1
      CASSANDRA_RACK: RACK2
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    depends_on:
      cassandra1:
        condition: service_started
    volumes:
      - C:\Users\ramak\Docker\cassandra-cluster-dev\SCMDC101\IND_BLR_DC_1\cassandra2:/var/lib/cassandra

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    hostname: cassandra3
    networks:
      - cassandra-net
    ports:
      - "9044:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
      CASSANDRA_CLUSTER_NAME: SCMDC101
      CASSANDRA_DC: USA_NY_DC_1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    depends_on:
      cassandra2:
        condition: service_started
    volumes:
      - C:\Users\ramak\Docker\cassandra-cluster-dev\SCMDC101\USA_NY_DC_1\cassandra3:/var/lib/cassandra

networks:
  cassandra-net:
    driver: bridge
