spring:
  application:
    name: apache-cassandra
  cassandra:
    port: 9042
    contact-points: cassandra1
    keyspace-name: fintech
    schema-action: none
    local-datacenter: IND_BLR_DC_1
    connection:
      connect-timeout: 10
    request:
      timeout: 5000
    controlconnection:
      timeout: 10000

logging:
  level:
    org:
      springframework:
        data:
          cassandra: DEBUG
